language: java
sudo: false
jobs:
  include:
    - script: mvn clean package
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "target/twitchbot-jar-with-dependencies.jar"
        skip_cleanup: true
        on:
          tags: true
